language: node_js
node_js:
  - 8
script:
  - cd ./serverless_api_automated_test/
  - npm install
  - npm install -g serverless
  - serverless deploy --region eu-central-1 --verbose
branches:
  only:
  - master