service: serverless_api_automated_test

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello
    name: serverless_api_automated_test-hello
    events:
      - http:
          method: get
          path: hello
          cors: true
      - http:
          method: post
          path: hello
          cors: true
  cheers:
    handler: handler.cheers
    name: serverless_api_automated_test-cheers
    events:
     - http:
         method: delete
         path: cheers
         cors: true
     - http:
         method: put
         path: cheers
         cors: true